#23 - [feat] 애플 로그인, 회원가입, 회원탈퇴 기능 구현
WooHyeopHa/Backend pull request #25
Opened 2024-08-16 09:28 UTC by ehyeok9

## 🔑 핵심 변경 사항

- 애플 회원가입, 로그인, 회원 탈퇴 기능 구현
- access, refresh 토큰 관련 기능 구현

## 🔖 핵심 변경 사항 외에 추가 변경 사항

- openfeign config 설정
- user entity 수정
- jenkins 파이프라인에 apple 키 파일 다운로드 단계 추가

## 🙌🏻 Reviewers에게 전하는 말

localhost에서는 ssl 인증서가 적용되지 않아, ngrok으로 ip 포워딩해서 시도해봤는데 redirectUrl로 요청이 넘어가 로직이 실행되지 않았습니다.
서버로 배포한 후 기능 테스트 해본 후, 다시 리팩토링 하겠습니다.

- 애플 키파일 다운로드 받으셔야 합니다 ! (resources -> apple -> 키파일)
- apple 및 jwt 환경변수 업데이트해두었습니다.
- 에러 처리 관련해서는 추후 한  번에 진행하겠습니다 !

## ✔️ PR Checklist

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

2024-08-18 09:14 UTC, lalabulla requested changes
전체적으로 잘 작성해주신 것 같습니다! 몇가지 피드백을 드리자면 (피드백 줄 실력은 안되는거 같지만😅)
- @Setter 는 한 번씩 더 고민해보고 도입하는 것이 좋은 방향이라고 생각해요! 
- 애플이 건네주는 AT/RT 혹은 자체 생성 AT/RT 혹은 둘 다 사용 -> 이부분을 좀 더 고민해보셨으면 좋겠습니다 어떤게 제일 효율적일지?
- 현재 서비스는 로그인 하지 않은 사용자는 이용 자체가 안되기 때문에 인증인가는 간단하게 필터 혹은 인터셉트로도 가능 할 것 같은 생각이 듭니다 (이부분은 저도 좀 더 공부하고 고민 해보겠습니당)
- 메소드명이나 변수명, 접근제어자들은 적절하게 잘 해주신거 같아요! 배우고 갑니다💨
- 덕분에 `OpenFeign`도 공부하는 계기가 되었습니다!

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
클라이언트 측과 Json 매칭 예외를 방지하기 위해 사용한 것일까요?.?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +    @Setter
`of`을 통해 객체를 생성하는 상황에서 해당 객체가 재사용되는 경우가 있을까요? (@Setter 사용에 관해)

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +        }
@getter 를 쓰지 않은 이유가 무엇인지 궁금해요💨

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +    private String user;
`idToken`과 `code`를 제외한 `state`, `user` 정보가 사용되는 곳이 있을까요? 만약 없다면 처음부터 받지 않는것도 좋을 것 같습니다!

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +        String appleRevokeUrl = "https://appleid.apple.com/auth/revoke";
openFeign을 사용하지 않고 추가로 RestTemplate을 쓰신 이유가 있나요?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
애플에서 받아온 AT와 RT 말고, 자체 생성 AT, RT를 만들어서 사용하신 이유가 있나요?
만약 애플에서 받아온 AT, RT는 단순 탈퇴만을 위한 토큰이라면 idToken을 받아오는 단계 (client_secret 생성 전)까지만 진행하고 자체적으로 AT, RT를 만들어 인증인가를 구현하는 것도 방법이라고 생각합니다 
현재는 약간 중복적인 느낌이 있는거 같아요!

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    private final String APPLE_AUTH_URL = "https://appleid.apple.com";
이 부분도 일관되게 설정파일(`AppleProperties`)에 담는 것이 좋을 것 같아요

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/OpenFeignConfig.java
> +    }
애플에게 공개키를 요청, 응답받을 때 시간관련 변수가 사용되나요?.?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/OpenFeignConfig.java
> +    }
공개키를 얻는 부분은 GET 메소드로 알고 있는데(바디가 없음), 어떤 예외 상황을 고려하신 걸까요?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/util/ApiResponse.java
> +        return new ApiResponse<>(responseCode, null);
예외 메세지도 같이 보내는 방향은 어떻게 생각하시나요?.?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> callback(HttpServletRequest request, HttpServletResponse response) throws IOException {
DTO 형식이 아닌 서블릿 형태로 받으시는 이유가 궁금합니당 (ex. AppleLoginResponse response)

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +        return ApiResponse.createError(ResponseCode.INTERNAL_SERVER_ERROR);
예외 처리는 나중에 따로 분리하실 계획이신가요?.?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> loginWithIdentityToken(HttpServletResponse response, @RequestBody AppleLoginResponse appleLoginResponse) throws BadRequestException {
해당 메소드가 컨트롤러 상 `callback`메소드와 거의 유사한 로직을 타는 것 같은데 어떤 상황에서 사용되는 메소드인가요?.?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/key/ApplePublicKeys.java
> +@Setter
공개키를 받아 주입하는 과정에서 @Setter가 필요한 것일까요?.? 아니라면 사용하신 이유가 궁금합니당

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +        User user;
변수들을 먼저 선언하신 이유가 궁금해요💨

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    public AppleToken.Response generateAuthToken(String code) throws BadRequestException{
여기서만 쓰이는 함수이면 private이 좋지 않을까 합니다

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            JsonNode jsonNode = objectMapper.readTree(payload.toJSONString());
`payload`에서 한번더` readTree`를 통해` jsonNode` 객체로 변환하신 이유가 궁금합니당

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            name = firstName + " " + lastName;
온보딩 로직상 닉네임을 추가로 받고 있기 때문에 해당부분은 필요하지 않을것 같아요!

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +                        .refreshToken(jwtService.createRefreshToken())
AT와 RT를 모두 저장하시는 이유가 궁금합니다! 보통 RT를 저장하고, RT를 통해 AT를 생성, 검증, 인증 단계를 거친다고 알고 있어서요. 또한 애플의 AT는 유효기간이 짧은 것으로 아는데 이부분은 어떻게 생각하시는지 궁금합니다

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    public String createClientSecretKey(String clientId) throws BadRequestException{
해당 메소드도 `private` 고려해보시면 좋을 것 같습니당

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
회원 탈퇴는 AT보단 RT가 좀 더 사용하기 편리해보이네요! 이유는 RT는 유저 객체에 저장된 정보이고 유효기간이 없어서 탈퇴시 요청하는 userId와 RT만 있다면 해당 메소드를 거치지 않아도 될 것 같습니다 (물론 탈퇴전 만료된 idToken을 위해 클라이언트측에서 한번 더 추가적인 로그인 작업이 필요하긴 합니다.)
어떻게 생각하시나요?!

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            ReadOnlyJWTClaimsSet jwtClaimsSet = signedJWT.getJWTClaimsSet();
해당 부분에 궁금한 점이 있습니당
`IdToken`은 애플로 부터 얻은 공개키 목록 중 `idToken`의 헤더와 일치하는 키를 찾고, 해당 키로 퍼블릭 키를 생성하여 파싱하는 것으로 알고 있습니다 
이부분은 따로 진행하지 않아도 그냥 파싱해서 `claim` 정보를 얻을 수 있는 것인가요?.?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/PrincipalUser.java
> +public class PrincipalUser implements UserDetails {
해당 부분이 자체 로그인이 없는 (소셜 로그인으로만 동작) 경우에도 사용하게 되나요?.?

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +@AllArgsConstructor
엔티티에서 @Setter 사용은 지양하는것이 좋을 것 같습니다 (필요한 필드에 한해서 메소드를 만드는 것이 좋을 것 같아요)
그리고 기본 생성자를 제외한 생성자는 직접 선언해서 만드시는 것이 좋을 것 같습니다 (PROTECTED는 유지하면서) @Builder 또한 해당 생성자 메소드에 선언하면 될 것 같구요!

2024-08-18 09:14 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            }
해당 부분의 위치를 `appleJwtUtils` 안으로 옮겨도 괜찮을 것 같다는 생각이 듭니다! 검증 후 한번 더 검증의 느낌이 있어서 검증은 하나의 클래스안에서 끝내고 오는게 괜찮을 수도 있을 것 같아요! 
한 번 고려해보시면 좋을 것 같습니다~

2024-08-21 07:10 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/util/ApiResponse.java
> +        return new ApiResponse<>(responseCode, null);
예외메시지도 클라이언트에게 같이 보내는 방향으로 수정하겠습니다.

2024-08-21 07:30 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/util/ApiResponse.java
> +        return new ApiResponse<>(responseCode, null);
d53feab7

2024-08-21 11:48 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> callback(HttpServletRequest request, HttpServletResponse response) throws IOException {
참고한 코드에서 서블릿으로 데이터를 받아서 그대로 따라했습니다 !
User, Name DTO 만든 후 AppleLoginResponse에 필드로 추가해서 수정하겠습니다.

2024-08-21 11:54 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +        return ApiResponse.createError(ResponseCode.INTERNAL_SERVER_ERROR);
네넵. RestControllerAdvice로 전역 에러 처리하는 것이 좋을 것 같아서 기능 구현에만 집중했습니다.
추후 따로 코드 리팩토링 하겠습니다.

2024-08-21 11:58 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/key/ApplePublicKeys.java
> +@Setter
습관적으로 Setter를 작성해둔 것 같습니다. ApplePublicKey, ApplePublicKeys에 있는 Setter는 지우도록 하겠습니다 !

2024-08-21 11:59 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/key/ApplePublicKeys.java
> +@Setter
9ab2c913

2024-08-21 12:00 UTC, minseo9974 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/key/ApplePublicKeys.java
> +@Setter
저는 Setter를 지양하는 편인데 거의 대부분 클래스마다 @Setter를 다 하신 이유가 있으실까요?
정말 필요한 경우외엔 생성자 또는 update~~~()처럼 메서드로 만들어 필요한 부분만 쓰는게 낫다고 생각합니다.

2024-08-21 12:00 UTC, minseo9974 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +@AllArgsConstructor
저또한 동의합니다. @Setter는 엔티티도 그렇고 dto에서도 지양하고 필요한 부분만 메서드로 만드는게 좋을것같습니다.

2024-08-21 12:00 UTC, minseo9974 commented on findMuse-API/src/test/java/com/whh/findmuseapi/ios/AppleServiceTest.java
> +        tokenResponse.setExpires_in("3600L");
테스트에서 set 사용하시려고 롬북 setter 쓰신거면  
ReflectionTestUtils 사용하시면 setter없이 주입이 가능합니다.

2024-08-21 12:01 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +        }
getter를 쓰면 메서드명이 snake_case가 되어서 직접 작성했습니다.

2024-08-21 12:07 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +    @Setter
애플 서버에 토큰 및 사용자 정보 요청보낼 때 사용됩니다 ! 보낼 때 외에는 재사용되지 않습니다.
Builder를 사용하여 가독성을 높이겠습니다.

2024-08-21 12:08 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +        }
필요없는 setter annotation과 get 함수들은 삭제하겠습니다 !

2024-08-21 12:11 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +        }
7d6e5793

2024-08-21 12:11 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +    @Setter
7d6e5793

2024-08-21 12:18 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> callback(HttpServletRequest request, HttpServletResponse response) throws IOException {
0cff3462

2024-08-21 12:24 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
사실 상관은 없지만, id_token 키로 값이 들어오기 때문에 혹시나 하는 예외를 예방하기 위해서 작성했습니다.
DTO 형식으로 변경하기 JsonNaming을 적용시켜야 할 것 같습니다 !

2024-08-21 12:24 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +    private String user;
아 넵 적용하겠습니다 !

2024-08-21 12:25 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +    private String user;
054363f6

2024-08-21 12:25 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    private final String APPLE_AUTH_URL = "https://appleid.apple.com";
아 넵 적용시키겠습니다.

2024-08-21 12:28 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    private final String APPLE_AUTH_URL = "https://appleid.apple.com";
6e0c892d

2024-08-21 12:31 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +        User user;
에러가 발생하면, catch 블록에서 값을 출력해보려고 먼저 선언시켜뒀었는데 변수가 사용될 때 선언하는 것으로 변경하겠습니다 !

2024-08-21 12:33 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            }
아 넵. 그 방식이 더 깔끔한 것 같습니다 ! 변경하겠습니다.

2024-08-21 12:37 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +        User user;
40714ed0

2024-08-21 12:37 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            }
40714ed0

2024-08-21 12:45 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/key/ApplePublicKeys.java
> +@Setter
아 테스트 코드 작성 과정에서 setter 메소드가 필요해서 작성해둔 것이었네요.

2024-08-21 13:35 UTC, lalabulla requested changes

2024-08-21 13:35 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
아하 그렇군요! 예외 방지 개념에서는 좋은 것 같습니다👍🏻
하나 여쭤볼것이 있는데, 로그인 후 클라이언트 쪽에서 idToken을 받아 서버 API 호출해서 넘겨주는 로직으로 진행되나요?.?

2024-08-21 13:45 UTC, lalabulla requested changes

2024-08-21 13:45 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +        }
생각해보니 DTO 변수들을 snake case로 명명하셧군요! JSON으로 받고, 넘어갔을 때를 고려해서 snake case로 작성하신걸까요?.?

2024-08-22 06:20 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
appleController에서 redirectUrl로 id_token을 전달 받아 회원가입이 진행되도록 해두었습니다 !(/callback)
성일님께서 애플 로그인을 어떻게 구현하실지 잘 몰라, 기존 블로그들에 있는 클라이언트로부터 id_token을 받아서 로그인하는 API도 만들어 두었습니다.(/token)

2024-08-22 06:21 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> loginWithIdentityToken(HttpServletResponse response, @RequestBody AppleLoginResponse appleLoginResponse) throws BadRequestException {
클라이언트가 이미 받은 id_token을 서버에 로그인 및 인증 요청할 때 사용됩니다 !

2024-08-22 06:27 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    public String createClientSecretKey(String clientId) throws BadRequestException{
아 네넵. 테스트 코드 작성하느라, Public으로 변경해두었던 것 같습니다.

2024-08-22 06:29 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    public String createClientSecretKey(String clientId) throws BadRequestException{
0ff99167

2024-08-22 06:37 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    public AppleToken.Response generateAuthToken(String code) throws BadRequestException{
마찬가지로 테스트 때문에 public으로 변경했던 것 같습니다. private로 변경하겠습니다.

2024-08-22 06:40 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +        String appleRevokeUrl = "https://appleid.apple.com/auth/revoke";
참고한 코드가 restTemplate를 사용하고 있어서 따라했습니다 ..
openFeign으로 변경하겠습니다 .. !

2024-08-22 06:46 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            JsonNode jsonNode = objectMapper.readTree(payload.toJSONString());
name -> firstName, lastName으로 되어 있어서 jsonNode로 .path("name").path("firstName") 이런식으로 작성해뒀는데, 나누는 게 좋을 것 같아서 nameNode랑 name을 분리했습니다. 
분리했으면 굳이 이렇게 나눠 쓸 필요가 없었는데, 해당 부분 삭제하겠습니다 !

2024-08-22 06:46 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            JsonNode jsonNode = objectMapper.readTree(payload.toJSONString());
0ff99167

2024-08-22 06:47 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    public AppleToken.Response generateAuthToken(String code) throws BadRequestException{
07ab2927

2024-08-22 07:02 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +        String appleRevokeUrl = "https://appleid.apple.com/auth/revoke";
a290709f

2024-08-22 07:37 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleLoginResponse.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
아하 그래서 두 개의 컨트롤러가 있었던거였네요🙆🏻‍♂️ 답변 감사합니다

2024-08-22 09:25 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            ReadOnlyJWTClaimsSet jwtClaimsSet = signedJWT.getJWTClaimsSet();
appleJwtUtil - verifyIdentityToken에서 애플에서 제시하는 5개의 검증 중 4개의 검증을 수행합니다.
퍼블릭 키를 생성하는 것은 jwt가 위변조되지 않은 것임을 검증하는 데 사용되는 것으로 알고 있습니다.
claim 추출은 jwt에서 바로 가져올 수 있습니다 !
원래 참고한 코드가 기존 방식(애플 서버에서 받아온 퍼블릭키들 전부 검증)으로 진행하면 !signedJWT.verify(verifier) 여기서 에러 발생할 것 같아서,
블로그들 참고해서 애플 공개키 중 헤더와 일치하는 키로만 검증을 진행하는 방식으로 변경했습니다.

혹시 로직에서 이상한 부분이 있다면 피드백해주시면 감사하겠습니다 !

2024-08-22 09:25 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            ReadOnlyJWTClaimsSet jwtClaimsSet = signedJWT.getJWTClaimsSet();
4c2e1d23

2024-08-22 09:26 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            name = firstName + " " + lastName;
네넵 해당 부분 삭제하게습니다 !

2024-08-22 09:26 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            name = firstName + " " + lastName;
0ff99167

2024-08-22 09:31 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/PrincipalUser.java
> +public class PrincipalUser implements UserDetails {
어어 사실 이건 초기(실패한) 방식으로 구현하다가 삭제 못하고 남긴 것 같습니다.
userDetails 상속 받으면 controller에서 AuthenticationPrincipal로 유저 정보 바로 받아올 수 있는 것으로 알고 있습니다.
인증/인가 적용한 후에 위 방식에 대해서도 얘기해보면 좋을 것 같습니다 !

위 엔티티는 일단 삭제해놓을까요 ?

2024-08-22 09:35 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/AppleToken.java
> +        }
받을 때 매칭되는 걸 고려해서 snake case로 작성해보았습니다 !

2024-08-22 09:36 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/dto/key/ApplePublicKeys.java
> +@Setter
민서님 의견 확인했습니다 ! setter 사용은 지양하도록 하겠습니다.

2024-08-22 09:38 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/OpenFeignConfig.java
> +    }
저는 Date로 사용하긴 했는데, 토큰 생성할 때 clientSecret을 포함하는데 여기서 jwt 생성시간 / 만료시간에 쓰입니다 !

2024-08-22 09:41 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/OpenFeignConfig.java
> +    }
token, revoke 요청은 post 메소드로 전달되는 것 같습니다 ! 이 상황에서 혹시나 null을 보내 에러가 발생할까봐 복붙해두었습니다.

2024-08-22 09:42 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +@AllArgsConstructor
네넵 해당 부분은 수정해두겠습니다 !

2024-08-22 09:46 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +@AllArgsConstructor
181dd960

2024-08-22 09:47 UTC, ehyeok9 commented on findMuse-API/src/test/java/com/whh/findmuseapi/ios/AppleServiceTest.java
> +        tokenResponse.setExpires_in("3600L");
ReflectionTestUtils 아 이런 유틸이 있는지 몰랐습니다. 조언 감사드립니다 !

2024-08-22 10:20 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
우움.사실 별 생각 없었는데 .. 다시 생각을 좀 해봤습니다. https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user에 보면
Apple’s servers may throttle your call if you attempt to verify a user’s Apple ID more than once a day. 라고 적혀져 있습니다 ! -> 2번 이상 refresh token 요청하면 제한할 수 있다.

유저가 우리 앱에 자주 방문해서 access 토큰이 2회 이상 발급이 필요하다면 -> 애플 서버에 2번 토큰 갱싱 요청을 보내야함 -> 어 근데 너무 많이 한다고 제한 걸었네 -> 유저가 앱 사용 못함.
이런 경우의 수가 있을 수도(?) 있을 것 같습니다.

그래서 앱 자체 AT, RT를 사용해서 유저의 인증/인가를 구현하는 것이 더 안전해보입니다.
어떻게 생각하시나요 ??
참고로 apple의 RT는 회원 탈퇴할 때 필요합니다 !

2024-08-22 10:29 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
오오.. 블로그 따라했는덷.. 아닛 그런 방법이 ?? 있었네요.. (심지어 블로그에도 refresh_token을 활용해도 좋을 것 같다고 적혀 있네요)
받잡겠습니다.

2024-08-22 10:30 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
767efc3d

2024-08-22 11:36 UTC, minseo9974 approved these changes
고생하셨습니다.

2024-08-22 15:55 UTC, lalabulla approved these changes
상세 답변 달아주셔서 감사합니다! LGTM👍🏻

2024-08-22 15:55 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/OpenFeignConfig.java
> +    }
아하 그렇군요! 제가 말씀드린건 `Request Body` 혹은 `Response Body` 상` LocalDate / LocalDateTime / LocalTime`을 타입으로 가지는 변수가 있는지 여쭤본 것이었습니다
말씀하신 Jwt 상의 생성 만료 시간은 암호와되어 client secret 변수안에 담기기 때문에 해당되지 않을 것 같네요😅
하지만 추후에 또 쓰일 가능성이 있어서(오픈 API관련) 지우지 않고 그대로 가져가도 좋을 것 같습니다! 👍🏻

2024-08-22 15:55 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
좀 찾아보니 정말 그렇네요! (실제로 여러번 엑세스토큰 재발급을 했을 때 제한이 걸리는 경우는 없었던거 같습니다. 검증과 발급이 약간 다른 의미일수도?) 하지만 혹시나를 대비해 혁규님이 말씀하신 플로우로 진행하는것이 좋아보입니다! 
AT는 버리고 RT만 유저엔티티에 저장해놓으면 좋을 것 같습니다👍🏻

2024-08-22 15:55 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            ReadOnlyJWTClaimsSet jwtClaimsSet = signedJWT.getJWTClaimsSet();
아하 제가 조금 이상하게 이해하고 있었네요! 말씀하신 것처럼 토큰의 위변조 검증에 퍼블릭키가 쓰이고 파싱과는 무관한 것 같습니다 친절답변 감사합니다🙌🏻

2024-08-22 15:55 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/PrincipalUser.java
> +public class PrincipalUser implements UserDetails {
아닙니다! 추후 혁규님이 인증/인가 구현하면서 쓰임 고려해보시면 좋을 것 같아요!

2024-08-23 09:22 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
반영해서 수정해놓겠습니다 ~!~!

2024-08-23 09:26 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +    }
a6803da5

2024-08-23 09:28 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/OpenFeignConfig.java
> +    }
아아 확인했습니다 !

2024-08-23 09:34 UTC, merged