[FIX] 모집글 피드백 수정
WooHyeopHa/Backend pull request #34
Opened 2024-08-30 08:47 UTC by minseo9974

#27 

## 🔑 핵심 변경 사항
- Entity <-> Dto 변환 수정
- 모집글 조회시 동시성 제어 추가 (timeout 5초 설정)

## 🔖 핵심 변경 사항 외에 추가 변경 사항
없음

## 🙌🏻 Reviewers에게 전하는 말
- 피드백 사항 최대한 반영했고 아직 기능이 필요해서 구현하지 못한 부분은 TODO로 표시해두었습니다.
- 동시성 제어 관련해서는 비관적 락을 사용했습니다. (데드락 상황을 최대한 피하고자 베타락 사용)

## ✔️ PR Checklist
- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

2024-08-30 09:10 UTC, ehyeok9 requested changes
issue, pr 템플릿 / github acton 스크립트 / gitignore 복원이 필요할 것 같습니다 .. !

2024-08-30 09:10 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/repository/PostRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
검색을 해보니 PESSIMISTIC_WRITE은 트랜잭션 충돌이 발생한다고 가정하고 -> 락을 걸고 -> 비즈니스 로직을 수행한다고 나옵니다 !
혹시 이렇게 구현하신 이유가 있을까요 ? 성능면에서 효율이 떨어질 것 같아서 질문 남깁니다 !

2024-08-30 09:10 UTC, ehyeok9 commented on .gitignore
> -application-env.properties
혹시 이것도 삭제하신 이유가 있을까요 ..?

2024-08-31 06:47 UTC, minseo9974 commented on .gitignore
> -application-env.properties
어 이거 삭제 한적이 없는데 제꺼에 업데이트가 안되어있었나 봅니다 
죄송합니다 이거 다시 추가할게요

2024-08-31 06:52 UTC, minseo9974 commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/repository/PostRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
저희 서버가 단일 디비 단일 서버이기 때문에 분산락을 구현하기보단 DB레벨에서 해결하고자 했습니다
다른 낙관적 락을 걸었을땐 데드락 이슈가 발생할 가능성이 있기때문에 비관적 락을 걸어서 트랜잭션간의 충돌을 더 확실하게 막고자 하였습니다 트래픽이 많이 몰리게되면 성능면 효율이 당연히 떨어집니다! 그부분은 어쩔 수 없기에
타임아웃 5초를 설정했습니다

2024-08-31 08:58 UTC, lalabulla requested changes
수정 반영 수고하셨습니다! 나머지 부분도 잘 작성해주신 것 같습니다

- `@NotBlank`는 `String`에만 적용할 수 있는걸로 알고 있습니다! (제가 기억하기론) 타입 구분하셔서 반영해주시면 감사하겠습니다
- 혁규님이 말씀해주신 것처럼 이슈, PR 템플릿 / 워크플로우 등 파일 복구 해주시면 좋을 것 같습니다!

2024-08-31 09:14 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/repository/PostRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
단일 서버이기에 가능한 "@Transactional 주석 처리 + save 호출"을 적용해보시는 건 어떻게 생각하세요 ..?
락보다 효율적인 방법인 것 같습니다 !
관련 블로그 첨부드립니다.

https://velog.io/@fishphobiagg/JPA-Spring-Boot-%EB%8F%99%EC%8B%9C%EC%84%B1-%EC%A0%9C%EC%96%B4%ED%95%98%EA%B8%B0-feat.%EC%83%81%ED%92%88-%EC%A3%BC%EB%AC%B8-%EC%84%9C%EB%B9%84%EC%8A%A4-%EC%98%81%EC%86%8D%EC%84%B1-%EC%BB%A8%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0

2024-09-01 12:47 UTC, ehyeok9 approved these changes
LGTM !

2024-09-05 14:34 UTC, lalabulla approved these changes
LGTM👍🏻

2024-09-05 14:40 UTC, merged