[feat] JWT 인증/인가 설정
WooHyeopHa/Backend pull request #35
Opened 2024-08-30 14:32 UTC by ehyeok9

#32 

## 🔑 핵심 변경 사항

- JwtAuthenticationFilter를 통해 로그인 요청을 제외한 모든 요청에 대해 JWT 토큰 검증
- SecurityConfig 기초 설정

## 🔖 핵심 변경 사항 외에 추가 변경 사항

없음

## 🙌🏻 Reviewers에게 전하는 말

테스트 코드 작성하면서 기능 작동하는지 확인해보았습니다 !
내일 시간이 된다면 swagger 설정한 후, Test API 만들어서 한 번 테스트 해보겠습니다 !

## ✔️ PR Checklist

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

2024-08-31 07:42 UTC, minseo9974 commented
혹시 다른 기존에 존재하는 Entity랑 제 모집글 service가 이전 버전으로 다시 올라가있던데 왜 중복건이 또 푸쉬되었나요??

2024-08-31 09:20 UTC, ehyeok9 reviewed
> 혹시 다른 기존에 존재하는 Entity랑 제 모집글 service가 이전 버전으로 다시 올라가있던데 왜 중복건이 또 푸쉬되었나요?? 

민서님이 이전에 dev-api 브런치에 push한 내용이 지금 반영된 것 같습니다 !
민서님 push -> 제가 jwt브런치 생성, 이 순서로 진행되어서 그런 것 같습니다.

2024-08-31 09:21 UTC, ehyeok9 commented
> 민서님이 이전에 dev-api 브런치에 push한 내용이 지금 반영된 것 같습니다 !
> 민서님 push -> 제가 jwt브런치 생성, 이 순서로 진행되어서 그런 것 같습니다.

2024-09-01 16:15 UTC, lalabulla requested changes
꼼꼼하게 잘 작성해주신거 같아요!👍🏻 역시 인증인가는 어렵군요,,
최대한 이해되는 선에서 리뷰했습니다! 
조금 복잡한 느낌이 있어서 추후 리팩토링이 진행되면 아주 좋을 것 같습니다!!
수고 많으셨습니다 :)

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> revokeAppleAccount(String code, Long userId) {
`@PathVariable` 혹은 `@RequestParam` 을 붙여주지 않아도 정상적으로 요청 받을 수 있나요?.?

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            .token(tokenResponse.getRefreshToken())
토큰 정보를 저장하지 않고 탈퇴 시에만 토큰을 요청하도록 바꾸셨네요!.! 좋은 것 같습니다 :)

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> + * AccessToken 만료 시에만 RefreshToken을 요청 헤더에 AccessToken과 함께 요청
만료 됐다는 응답을 받은 경우 RT만 보내는 것이 아닌 RT와 AT를 함께 요청하는 이유는 무엇인가요?.?

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        // 만약 일치한다면 AccessToken과 RefreshToken을 재발급해준다.
리프레쉬 토큰의 재발급에 대해서 한번 고민해보시면 좋을 것 같습니다.
혁규님의 로직 상 AT와 RT의 갱신주기가 동일하게 되는데 보틍은 AT가 훨씬 짧고, RT는 어느정도 긴 것이 일반적이니까요!
RT가 유효하지 않은 경우(RT의 생명이 끝난 경우)에만 기존의 RT와 비교 후 재발급을 해주는 것도 방법일 것 같습니다

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        if (jwtService.isTokenValid(refreshToken)) {
해당 메소드를 호출하는 경우는 현재 70번째 줄밖에 없는 것 같습니다. 
즉 이 메소드를 호출하기 위해서 이미 isTokenValid 메소드를 거치고 호출된 상태인데 추가적으로 한 번 더 검증하는 이유가 궁금합니다🤔

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +    }
해당 메소드의 위치는 문맥 상 jwtService가 조금 더 적절해보입니다!

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        checkAccessTokenAndAuthentication(request, response, filterChain);
만약 RT와 AT가 둘 다 유효하지 않는 경우 다시 로그인이 진행되는 걸까요?.?

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/SecurityConfig.java
> +                writer.flush();
반복되는 부분은 메소드로 빼는 것이 어떨까요?.?

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/util/Utils.java
> +    public static void sendErrorResponse(HttpServletResponse response, int status, ResponseCode responseCode) throws IOException {
해당 메소드가 어떤 상황에서 쓰이는지 궁금합니다! (필터 상 에러메세지는 SecurityConfig에서 만들고 계셔서)

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtExceptionFilter.java
> +            ResponseCode.TOKEN_EXPIRED);
RT가 만료된 경우에는 토큰이 만료되었단 메세지 보다는 재로그인이 필요합니다와 같은 메세지가 어떨까용 (만약 RT가 만료시 재로그인 로직이라면)

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtExceptionFilter.java
> +        }
해당 부분이 궁금해서 여쭤봅니다!
앞에서 1번필터 `JwtAuthenticationFIilter`를 거친 후 해당 필터인 `JwtExceptionFilter`를 거치게 되는 것인가요?
맞다면 어떻게 23번에서 RT 만료 예외를 만들어 낼수 있는지? 궁금합니다.

2024-09-01 16:15 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +            return; // 현재 필터 진행 막기
`Config`에서 url 패턴 설정을 해주어도 해당 필터를 거치게 되는 경우가 발생하나요?.?

2024-09-02 01:24 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/SecurityConfig.java
> +                writer.flush();
그렇게 리팩토링하는 편이 더 깔끔할 것 같네요 ! 수정해서 커밋하겠습니다.

2024-09-02 01:34 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/config/SecurityConfig.java
> +                writer.flush();
7b786e6b

2024-09-02 01:39 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> revokeAppleAccount(String code, Long userId) {
Spring MVC에서 annotation 붙여주지 않으면 @RequestParam으로 자동적으로 처리한다고 알고 있습니다 !
명시적으로 이해하기 쉽게 annotation 붙이겠습니다 !

참고로 userId는 추후에 authenticationprincipal로 유저 정보 받아오도록 수정할 예정입니다.

2024-09-02 01:40 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> revokeAppleAccount(String code, Long userId) {
7b786e6b

2024-09-02 01:41 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/service/AppleService.java
> +            .token(tokenResponse.getRefreshToken())
넵 ! 활용되는 곳이 회원탈퇴 외에 사용되지 않아, RT를 저장하지 않고 회원탈퇴 시에만 애플 서버에서 받아오는 것으로 리팩토링 하였습니다. 칭찬 감사드립니다 !

2024-09-02 01:51 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +    }
넵 수정하겠습니다 !

2024-09-02 01:57 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        if (jwtService.isTokenValid(refreshToken)) {
이미 필터링된 refreshToken이 매개변수로 들어와 token이 유효한지 검증할 필요가 없군요 ..!
놓친 부분이었던 것 같습니다. 피드백 감사합니다 !

2024-09-02 03:22 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        checkAccessTokenAndAuthentication(request, response, filterChain);
현재 구현된 로직으로는
RT, AT 둘 다 유효하지 않음 -> 사용자가 SecurityContextHolder에 저장되지 않음 -> SecurityFilterChain에서 AuthenticationEntryPoint 호출 -> 클라이언트에 에러메시지 전달 순 입니다.
그러므로 만약 RT, AT 모두 만료된다면 UNAUTHORIZED_REQUEST‎에러를 반환하므로 클라이언트에서 재로그인을 요청해야 하지 않을까 싶습니다.

2024-09-02 04:09 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/ios/controller/AppleController.java
> +    public ApiResponse<?> revokeAppleAccount(String code, Long userId) {
아하 그건 몰랐네요!! 감사합니다🙌🏻

2024-09-02 04:13 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        checkAccessTokenAndAuthentication(request, response, filterChain);
아~~ 그런 로직으로 진행되는군요! 설명 감사합니다!!

2024-09-02 04:22 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +            return; // 현재 필터 진행 막기
url 접근 설정을 허용해주면, filter를 거치지 않아 해당 부분은 삭제해도 될 것 같습니다 !
JwtAuthenticationFilter를 먼저 구현하고 security 설정을 해서 중복된 부분이 발생한 것 같습니다.
수정해두겠습니다 !

2024-09-21 08:49 UTC, lalabulla approved these changes

2024-09-21 10:28 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> + * AccessToken 만료 시에만 RefreshToken을 요청 헤더에 AccessToken과 함께 요청
현재 코드 상에는 RT가 만료되면 null 값이 되고, AT를 추출해서 user email을 얻기 위함입니다 !
어떻게 수정할 지 고민하고 있습니다.

2024-09-21 10:29 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        // 만약 일치한다면 AccessToken과 RefreshToken을 재발급해준다.
흐음 그렇군여 !
한 번 수정해보겠습니다 !

2024-09-21 11:37 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +        // 만약 일치한다면 AccessToken과 RefreshToken을 재발급해준다.
1. 기본적으로 사용자는 요청 헤더에 AccessToken만 담아서 요청
2. AccessToken 만료 시에만 RefreshToken을 담아서 요청 (AccessToken 포함 안 해도 됨)
3. AcessToken은 만료 안 되었는데, RefreshToken 만료됨
-> Clinet에서 Refresh 재발급 API endpoint로 요청
4. RefreshToken 만료되고, AccessToken도 만료됨
-> 로그인 다시

위 흐름으로 로직 다시 작성했습니다 !

2024-09-22 05:10 UTC, minseo9974 approved these changes
고생하셨습니다

2024-09-22 05:10 UTC, minseo9974 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +            checkRefreshTokenAndReIssueAccessToken(response, refreshToken);
보통 refersh 토큰을 레디스에서 관리하는게 Expire설정과 함께 캐싱효과 늘리면서 더욱 효율적인 관리가 우수한데 혹시 DB저장 방식을 이용하시는 이유가 있을까요?

2024-09-22 05:10 UTC, minseo9974 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +    public void checkAccessTokenAndAuthentication(HttpServletRequest request,
이부분도 마찬가지로 로그인할때마다 DB에서 사용자 정보를 가져오게되면 너무 자주 DB와 통신을 하게될것같은데 
유저정보도 맨 처음 액세스 토큰 인증시 캐싱해두었다가 refresh토큰과 동일한 기간을 부여해서 캐싱해둔걸 가져오는 방법은 어떠신가요?

2024-09-22 05:32 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +            checkRefreshTokenAndReIssueAccessToken(response, refreshToken);
trade off가 있는 것 같습니다 !
변명이지만, 현재 저희 free tier resource 상 nginx, jenkins, api-server, chat-server가 돌아가고 있기에 시스템 메모리인 1GB는 거의 다 사용하고 있는 상태이고, swap memory 거의 1GB가 사용 중입니다.
채팅 서버를 구현하면서 kafka, zookeeper container도 띄워야되기 때문에 적용하지 않았습니다 !
추후에 서비스가 배포되고 트래픽이 늘어나게 된다면 적용 고려해보도록 하겠습니다 !

2024-09-22 05:34 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/jwt/filter/JwtAuthenticationFilter.java
> +    public void checkAccessTokenAndAuthentication(HttpServletRequest request,
redis를 적용하면 I/O 작업이 줄어들어 확실히 응답 속도 측면애서 이점이 있겠군요 !
위에 언급한 내용들이 해결된다면, 적용해보도록 하겠습니다 !

2024-09-22 08:09 UTC, merged