[feat] 동행 관련 기능
WooHyeopHa/Backend pull request #41
Opened 2024-09-05 14:46 UTC by minseo9974

## 🔑 핵심 변경 사항

동행 지원 관련된 기능들을 추가했습니다.
참여 수락, 거절, 리스트 반환 등등..

## 🔖 핵심 변경 사항 외에 추가 변경 사항

## 🙌🏻 Reviewers에게 전하는 말

## ✔️ PR Checklist

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

2024-09-06 07:02 UTC, lalabulla requested changes
꼼꼼하게 잘 작성해주신거 같아요!! 👍🏻 고생하셨습니당
보면서 하나 든 생각이 작성자 일치 여부를 API 호출 후 검사하고 있는 상황인데, 애초에 작성자가 아니라면 신청자 목록을 볼 수 없어야 하는 것 아닌가? 라는 생각이 들었습니다.
즉, 모집글 상세를 들어가는 순간 판별해서 클라쪽에서 다르게 UI를 보여줘야 하는 것 같다는 생각이 들어습니다. 어떻게 생각하시나요?.?

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/service/impl/VolunteerServiceImpl.java
> +                Infos.InvieteStatus.Wait);
오호 이렇게 하면 `Infos.InviteStatus.Wait` 인 사람과 아닌사람 구분해서 가져올 수 있군요! 배워갑니다~~

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/service/impl/VolunteerServiceImpl.java
> +                .collect(Collectors.toList());
함수화 시키는 방법도 고민해보시면 좋을 거 같슴다! (두번밖에 안쓰여서 애매하긴 하지만요,,😅)

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/service/impl/VolunteerServiceImpl.java
> +                .collect(Collectors.toList());
이 부분은 함수로 추출하는 것이 어떨까용?.?

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/controller/VolunteerController.java
> +    public ApiResponse<?> cancelVolunteer(@RequestParam Long volunteerId, @RequestParam Long userId) {
`PostId`가 아닌 모집글 작성자 ID를 받는 이유가 궁금해용

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/controller/VolunteerController.java
> +    public ApiResponse<?> getPostVolunteerList(@PathVariable Long postId, @RequestParam Long userId) {
여기서 받는 `userID`는 이 API를 호출하는 사람의 `userID`인가요?.? 아니면 말 그대로 작성한 사람의 `userID`인가요?.?

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/controller/VolunteerController.java
> +    public ApiResponse<?> acceptVolunteer(@PathVariable Long postId, @RequestParam Long writerId, @RequestParam Long targetId) {
클라이언트 쪽에서 모집글 작성자 ID를 저장해 놓나요?.?(작성자ID는 모집글 조회 시에도 알 수 있습니다)

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/entity/Volunteer.java
> +    }
상태를 변경하는 경우라면 boolean이니 값을 인자로 받는 것도 좋지만, 함수 호출 시 인자 없이 값을 반대로 바꿔주는 형태도 괜찮을 것 같습니다 :)

2024-09-06 07:02 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/service/impl/PostServiceImpl.java
> +    @Transactional
해당 메소드에 `@Transactional `이 필요한 이유가 궁금해요!

2024-09-09 12:01 UTC, ehyeok9 approved these changes
규현님이 정성스럽게 코멘트 달아주신 것 같습니다 !!
LGTM

2024-09-10 05:55 UTC, minseo9974 commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/service/impl/VolunteerServiceImpl.java
> +                Infos.InvieteStatus.Wait);
여기를 통해서 위 코멘트에 리플라이 달도록 하겠습니다!
음 말씀 하신대로 작성자가 아니라면 애초에 신청자 목록을 볼일 없으니까 일치 여부를 따로 할 필요가 없습니다!
저는 일단 완벽하게 바늘구멍이라도 막자 주의여서 무의식 흐름대로 일단 막았는데 
이부분은 보안이 그렇게 중요시되는 부분이 아니여서 제 생각도 이렇게까지 막을필요가 없을것 같네요!!

2024-09-10 05:57 UTC, minseo9974 commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/service/impl/VolunteerServiceImpl.java
> +                .collect(Collectors.toList());
음 몇번 안쓰여서 거슬리긴하지만 함수화하는편이 조금더 깔끔할려나요
(저는 정말 여러군대에서 여러번쓰이는것만 함수화하는 편이여서 고민되네요..!!)

2024-09-10 14:16 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/post/service/impl/VolunteerServiceImpl.java
> +                .collect(Collectors.toList());
이부분은 민서님이 원하시는 대로 하시면 좋을 거 같아요~~

2024-09-20 14:55 UTC, lalabulla approved these changes

2024-09-22 04:36 UTC, merged