[feat] 프로필 등록 기능
WooHyeopHa/Backend pull request #42
Opened 2024-09-21 13:12 UTC by ehyeok9

## 🔑 핵심 변경 사항

온보딩 과정에서 프로필을 등록하는 기능을 구현했습니다.
information(birthYear, gender ..) / location / taste 3개로 나눠서 API를 구현했습니다.
그 이유는 온보딩 과정에서 건너뛰기가 가능해서 다음으로 넘어갈 때마다 backend로 요청하는 방식했기 때문입니다.

따로 프로필 수정 기능도 구현하려 했지만, 개발하시는 분의 생각이 있으실 것 같아 따로 만들진 않았습니다.
취향 update는 register와 동일한 방식으로 진행되기에 이 부분만 추가로 구현했습니다 !

## 🔖 핵심 변경 사항 외에 추가 변경 사항

- data.sql 카테고리 및 취향 업데이트

## 🙌🏻 Reviewers에게 전하는 말

pem key가 없어서 아직 테스트를 못해봤습니다.
jwt 인증 테스트 -> refactoring -> merge -> 프로필 등록 테스트 -> refactoring -> merge
위 순서대로 진행하겠습니다.

## ✔️ PR Checklist

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

2024-09-23 08:56 UTC, lalabulla requested changes
전체적으로 잘 작성해주신 것 같습니다!!! 수고 많으셨습니다!
두가지 정도 궁금한 점이 있는데요,
1. 컨트롤러에서 `@AuthenticationPrincipal`로 `User` 객체를 받아오고 계신데, 해당 `User` 엔티티가` UserDetails`를 구현하고 있지 않아도 무방한가요?.? 
2. 닉네임 중복검사는 어떻게 구현하실 계획이신지 궁금합니당

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/resources/data.sql
> +-- 전시회 하위 항목
깔끔 정리 감사합니다🫡

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/constant/Infos.java
> +                    .orElseThrow(() -> new CustomBadRequestException("유효하지 않은 성별 값이 입력되었습니다."));
여기도 예외처리가 들어가야 하는군요! 배워갑니다

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/repository/UserTasteRepository.java
> +    void deleteByUser(User user);
해당 메소드는 유저가 취향을 변경하였을 때 사용되는 되는 것일까요?.?
만약 그렇다면 메소드를 호출하는 것도 좋지만, 연관관계 상 고아객체 삭제 옵션을 사용하는 것도 방법일 것 같습니다!

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/dto/request/UserProfileInformationRequest.java
> +        String gender
닉네임은 필수로 받고, 생년월일과 성별은 건너뛰기가 가능한 걸로 구분되게 변경된 것으로 알고있습니다.
따로 구분헤서 받을 필요는 없는 걸까요?.?

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/dto/request/UserProfileTasteRequest.java
> +public class UserProfileTasteRequest {
위에 DTO들은 record 키워드를 사용하셨는데, 해당 DTO는 사용하지 않으신 이유가 궁금합니당 (List 이슈인가요?)

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +        userRepository.save(user);
`userRepository.save(user);`를 직접 명시하는 것도 직관적이지만, `@Transactional `의 더티체킹을 사용하는 것도 고려해보시면 좋을 것 같습니다!

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +        userTasteRepository.deleteByUser(user);
`UserTaste` 객체들을 지워지지만, 연관관계를 맺은 `User`쪽의 `UserTaste` 정보들까지 함께 지워지는 걸까요?.?

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +                                return userTaste;
`User` 엔티티로부터 선호하는 `Taste`를 조회하는 일이 없다면 굳이 유저쪽 연관관계에 생성한 `UserTaste` 객체를 넣어주지 않아도 괜찮을까요?🤔

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +
Mapper를 위해 `@setter`사용은 필수적인가요?.? 묶어서 메소드화 하는 방법도 고려해보시면 좋을 것 같습니다! (안정성고려)

2024-09-23 08:56 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +    private int birthYear;
생년월일 `String` 에서` int`로 변경하신 이유 궁금해용

2024-09-23 09:01 UTC, ehyeok9 commented on findMuse-API/src/main/resources/data.sql
> +-- 전시회 하위 항목
제가 더 감사합니다..

2024-09-23 09:02 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/common/constant/Infos.java
> +                    .orElseThrow(() -> new CustomBadRequestException("유효하지 않은 성별 값이 입력되었습니다."));
저도 규현님 리뷰 방식 배워갑니다 !!

2024-09-23 09:08 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/dto/request/UserProfileInformationRequest.java
> +        String gender
아 figma 왼쪽 위에 변경된 사항이 있었군요. refactoring 하겠습니다 !

2024-09-23 09:10 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/dto/request/UserProfileTasteRequest.java
> +public class UserProfileTasteRequest {
record에서 하위 클래스를 만들어본 적이 없어서, class로 구현을 했습니다 !
찾아보니, 똑같이 하나 만들면 되네영. dto는 record로 통일하겠습니다.

2024-09-23 09:12 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/repository/UserTasteRepository.java
> +    void deleteByUser(User user);
와.. 고아 객체 삭제 옵션은 처음 들어보는데 신기하네요 !
한 번 적용시켜 보도록 하겠습니다.
한 수 배웁니다..

2024-09-23 09:13 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +        userRepository.save(user);
아 넵넵..! transactional 데이터 일관성 때문에만 썼지, 더티 체킹에 대해선 몰랐네요 !!
이것도 하나 배워갑니다.

2024-09-23 09:18 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +        userTasteRepository.deleteByUser(user);
제가 연관관계에 좀 많이 약하네요 ..
검색해봤더니, User List<UserTaste>를 업데이트 해주지 않으면 이전의 데이터가 남아있을 수도 있다고 합니다 .. !
이전에 리뷰 주셨던 고아 객체 설정 적용이나 Cascade 설정을 통해 해결하겠습니다.

2024-09-23 09:20 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +    private int birthYear;
생년월일 유효성 검사를 할 때, int로 변환하여 이상 값을 체크한 후 저장하는 방식으로 구현하였습니다. 
그래서 int 값으로 설정하였는데, string으로 변환시켜놓을까요 ?

2024-09-23 09:21 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +
mapper를 사용하려면 setter가 필수적입니다 .. 
User의 entity의 경우 안정성을 고려해 빌더를 적용시키겠습니다 !

2024-09-23 09:26 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +                                return userTaste;
만약 User entity의 List<UserTaste>를 직접 조회 하지 않는다면 객체를 넣어주지 않아도 상관 없지만 (userTasteRepository.findbyUser 사용 경우)

데이터 무결성을 위해 user 필드에도 넣어주는 것이 좋을 것 같습니다.
어떻게 반영할지는 고민한 후 적용해보겠습니다 !

User Entity 연관 관계를 전혀 고려하지 못하고 있었는데 집어주셔서 감사합니다.

2024-09-23 10:54 UTC, minseo9974 commented
잘봤고 저도 더티 채킹 부분이나 이러한부분을 말씀드리려 했는데 이미 위에서 언급하셔서 생략하겠습니다!
혹시 본문에서 프로필 수정기능에 대해 개발을 미루셨다고 하셨는데 구체적으로 어떤 기능인지 알 수 있을까요?

2024-09-23 10:55 UTC, minseo9974 approved these changes

2024-09-23 11:39 UTC, lalabulla commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +    private int birthYear;
아~~~ 그부분은 제가 고려를 못했네요!! int로 진행하시면 좋을 것 같습니다👍🏻

2024-09-23 22:46 UTC, ehyeok9 commented
@minseo9974 
mypage -> profile_change 부분입니다.. ! 피그마 마이페이지 탭에 있습니다 !

2024-09-23 22:58 UTC, ehyeok9 commented
@lalabulla 
감사합니다 !
1. JwtAuthenticationFilter에서 Access Token을 통해 인증된 사용자는 saveAuthentication 메서드를 거칩니다. 이 과정에서 User 정보를 바탕으로 UserDetails 객체를 생성한 후, UsernamePasswordAuthenticationToken을 사용해 해당 사용자를 인증된 사용자로 설정합니다. 이때, 이전에 생성된 UserDetails의 권한을 함께 설정해 줍니다. 마지막으로, 생성된 인증 정보를 SecurityContextHolder에 저장하여, 이후 @AuthenticationPrincipal 애노테이션을 사용할 수 있게 합니다.

2. 닉네임 중복 기능 관련해서도 놓쳤네요 .. ㅋㅋㅋㅋㅋㅋㅋㅋ 반영해놓도록 하겠습니다.

2024-09-23 23:14 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/dto/request/UserProfileTasteRequest.java
> +public class UserProfileTasteRequest {
00540024

2024-09-23 23:36 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/dto/request/UserProfileInformationRequest.java
> +        String gender
69189e1c

2024-09-23 23:36 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +        userRepository.save(user);
69189e1c

2024-09-23 23:36 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/entity/User.java
> +
69189e1c

2024-09-24 00:11 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +                                return userTaste;
ae960760

전이 영속성 설정을 통해 List<UserTaste>에 추가해주는 것으로 이슈 해결하였습니다 !

2024-09-24 00:14 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/service/UserService.java
> +        userTasteRepository.deleteByUser(user);
ae960760

고아 객체 설정을 통해 List<UserTaste>를 clear 함으로써 데이터 무결성을 구현했습니다

2024-09-24 00:15 UTC, ehyeok9 commented on findMuse-API/src/main/java/com/whh/findmuseapi/user/repository/UserTasteRepository.java
> +    void deleteByUser(User user);
ae960760

고아 객체 설정 완료 했습니다 !

2024-09-24 02:14 UTC, lalabulla commented
> 1. saveAuthentication

2024-09-24 02:19 UTC, lalabulla approved these changes
LGTM👍🏻

2024-09-29 11:17 UTC, merged